name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["logcat"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description
      description: Please describe the issue in your own words
      placeholder: Issues without a meaningful description are closed
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logcat Output
      description: Long press inside this box and select "Paste"
      render: shell
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Wiki Confirmation
      description: By submitting this issue, you confirm checking the [Wiki](https://github.com/SamSprung/SamSprung-TooUI/wiki)
      options:
        - label: I have read the wiki and included a valid log
          required: true
