name: Android CI

on:
  push:
    branches: [ launcher ]

permissions:
  contents: read
  actions: write

jobs:
  clean:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
    - name: Remove artifacts
      continue-on-error: true
      uses: c-hive/gha-remove-artifacts@v1.3.0
      with:
        age: '2 days' # '<number> <unit>', parsed by Moment.js

    - name: Purge cache
      continue-on-error: true
      uses: MyAlbum/purge-cache@v1
      with:
        max-age: 172800 # 2 days, default: 7 days since last use

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleGithubRelease

    - uses: r0adkll/sign-android-release@v1
      name: Sign app APK
      # ID used to access action output
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/github/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.STOREPASS }}
        keyPassword: ${{ secrets.KEYPASS }}
      env:
        # override default build-tools version (29.0.3) -- optional
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Retrieve commit identification
      run: |
         GIT_BRANCH=$(git name-rev --name-only HEAD)
         echo "GIT_BRANCH=${GIT_BRANCH}" >> $GITHUB_ENV
         GIT_HASH=$(git rev-parse --short HEAD)
         echo "GIT_HASH=${GIT_HASH}" >> $GITHUB_ENV

    - uses: actions/upload-artifact@v4
      with:
        name: SamSprung-${{ env.GIT_HASH }}
        retention-days: 1
        path: ${{steps.sign_app.outputs.signedReleaseFile}}

    - uses: SamSprung/action-github-releases@v1.0.0
      if: ${{ github.event_name != 'pull_request' }}
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "sideload"
        prerelease: ${{ env.GIT_BRANCH != 'launcher' }}
        title: SamSprung-${{ env.GIT_HASH }}
        files: ${{steps.sign_app.outputs.signedReleaseFile}}
